<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="NguyenTrung" failures="4" tests="9" name="Test" time="51.766" errors="0" timestamp="2022-05-07T20:43:36 ICT">
  <testcase classname="TestASM2.Test.TestLoginExcelData" name="multiLogin" time="2.647"/>
  <testcase classname="TestASM2.Test.TestLoginExcelData" name="multiLogin" time="0.476"/>
  <testcase classname="TestASM2.Test.TestLoginExcelData" name="multiLogin" time="2.754">
    <failure type="java.lang.AssertionError" message="expected [Online Entertainment] but found [Login Online Entertainment]">
      <![CDATA[java.lang.AssertionError: expected [Online Entertainment] but found [Login Online Entertainment]
at TestASM2.Test.TestLoginExcelData.multiLogin(TestLoginExcelData.java:68)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- multiLogin -->
  <testcase classname="TestASM2.Test.TestInsertUser" name="multiInsert" time="4.885"/>
  <testcase classname="TestASM2.Test.TestInsertUser" name="multiInsert" time="5.353">
    <failure type="java.lang.AssertionError" message="expected [Error: Error while committing the transaction] but found [User inserted!!]">
      <![CDATA[java.lang.AssertionError: expected [Error: Error while committing the transaction] but found [User inserted!!]
at TestASM2.Test.TestInsertUser.multiInsert(TestInsertUser.java:84)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- multiInsert -->
  <testcase classname="TestASM2.Test.TestUpdateUser" name="multiUpdate" time="4.369"/>
  <testcase classname="TestASM2.Test.TestUpdateUser" name="multiUpdate" time="4.265">
    <failure type="java.lang.AssertionError" message="expected [User Updated!!] but found [User Updated]">
      <![CDATA[java.lang.AssertionError: expected [User Updated!!] but found [User Updated]
at TestASM2.Test.TestUpdateUser.multiUpdate(TestUpdateUser.java:81)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- multiUpdate -->
  <testcase classname="TestASM2.Test.TestDeleteUser" name="multiDelete" time="3.791"/>
  <testcase classname="TestASM2.Test.TestDeleteUser" name="multiDelete" time="3.909">
    <failure type="java.lang.AssertionError" message="expected [Error: Error while committing the transaction] but found [User Deleted]">
      <![CDATA[java.lang.AssertionError: expected [Error: Error while committing the transaction] but found [User Deleted]
at TestASM2.Test.TestDeleteUser.multiDelete(TestDeleteUser.java:76)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- multiDelete -->
</testsuite> <!-- Test -->
